### ISSUE TITLE
Audio output broken on firmware 1.0.0

### ISSUE THREAD

**Issue by yuukieve** [switchbrew/libnx#197]
Audio output does not work on 1.0.0. I tested with all of the audio examples from [switch-examples](https://github.com/switchbrew/switch-examples), playing an MP3 with [NX-Shell](https://github.com/joel16/NX-Shell), and playing a game with [mGBA](https://github.com/mgba-emu/mgba) and all of them were completely silent; I tested with NROs compiled with the latest libnx. Here is the output from the audio switch-examples:

* **audren-simple.nro:** https://i.imgur.com/nu6Zw6K.jpg
* **echo.nro:** https://i.imgur.com/dLAVCPM.jpg
* **playtone.nro:** https://i.imgur.com/We7lqzw.jpg

I believe the return result in `audren-simple.nro` may be the problem, as [0x499](https://github.com/switchbrew/switch-examples/blob/master/audio/audren-simple/source/main.c#L45) is the `Invalid buffer address` failure case. It seems a [similar issue may have been fixed in the past](https://github.com/switchbrew/libnx/blob/81d56a9e237ea6f18747c49f0629fbcaa6c3e1db/nx/source/services/audren.c#L88) but audio output remains broken.

**Comment by yellows8** [comment]
No output from echo example is normal when an audio-input isn't connected.

Did you ever try audio on 1.0.0 before?

**Comment by yuukieve** [comment]
I haven't tried it beforehand, unfortunately.

**Comment by yellows8** [comment]
libnx audren currently doesn't support pre-3.0.0 (same error on both 1.0.0/v2.x).

Not sure what broke with audout. :-/

**Comment by yellows8** [comment]
Try this: 
[playtone_libnxv141_with20204e3c.zip](https://github.com/switchbrew/libnx/files/2528354/playtone_libnxv141_with20204e3c.zip)

**Comment by yellows8** [comment]
[playtone_libnxv131.zip](https://github.com/switchbrew/libnx/files/2535244/playtone_libnxv131.zip)

**Comment by yellows8** [comment]
Also this: 
[audren-simple_audrenrev1.zip](https://github.com/switchbrew/libnx/files/2536473/audren-simple_audrenrev1.zip)

**Comment by yuukieve** [comment]
Tested both; audren-simple inits everything with no error codes and plays sound correctly, playtone gives no output/silence.

**Comment by yellows8** [comment]
With testing on IRC, apparently audout was broken since the very first libnx release. :-(

**Comment by pixel-stuck** [comment]
No audio output on 1.0

**Comment by yellows8** [comment]
[playtone_volume2.zip](https://github.com/switchbrew/libnx/files/2540269/playtone_volume2.zip)

**Comment by yuukieve** [comment]
No audio output on 1.0.0 with the build from `playtone_volume3.zip`; [here](https://i.imgur.com/Hl6qEwi.jpg) is the extra output that was added.

**Comment by yellows8** [comment]
Don't know what else to try. :-/

**Comment by yellows8** [comment]
Regarding audren see: 8767ea798b7c5a6196ff61a22ce29f32569503a8

**Comment by yellows8** [comment]
Are you all testing this under an Application or LibraryApplet/Album?

**Comment by yuukieve** [comment]
I tested this under Atmosphère's album redirection with the latest nx-hbloader hbl.nsp each time.

**Comment by yellows8** [comment]
Try with Application?

**Comment by fincs** [comment]
audren should be fixed with 1.6.0.

audout still needs testing.

**Comment by yellows8** [comment]
Still waiting on applet-Application testing/debugging.....

**Comment by yellows8** [comment]
Pinging @yuukieve again...

**Comment by yuukieve** [comment]
My apologies @yellows8, but I still can't seem to boot hbmenu or any NRO from an application, both with Ams and stock with PegaSwitch+nspwn.js, I get a crash with 2345-0031, so I have not been able to test this. I've not made any progress on debugging why this is the case, either.

**Comment by yellows8** [comment]
Can you modify libnx to debug it?

**Comment by yuukieve** [comment]
Per IRC, had to edit `hbl.json` and recompile nx-hbloader for PPT S JP and was able to launch hbmenu from it successfully, and `playtone.nro` remained silent, so the issue doesn't seem to be dependent on application type.

**Comment by fincs** [comment]
Anyone else still on 1.0 who could try to shed some light on this issue?

**Comment by fennectech** [comment]
Any caviats on downgrading from 7.0.1 to 1.0?

**Comment by pixel-stuck** [comment]
I've got a 1.0, willing to test whatever. From memory, audren worked fine, just not audout (which several homebrew use for sound); I was going to try to do some IPC logging via a mitm of audout but I got sidetracked on that

**Comment by yellows8** [comment]
Can someone try moving the audoutStartAudioOut call before the sample-rate printf, and check if the displayed output changes?

**Comment by yellows8** [comment]
Can someone try using audout from hbl running under flog, with 1.0.0? Ideally with the official flog launch method.

**Comment by cheesycod** [comment]
This issue is 2 years old, can we close it please since it was most likely fixed

**Comment by yellows8** [comment]
AFAIK it is not fixed, this will *not* be closed until it's proven to be fixed.
